spring:
  application:
    name: gateway
  #    fetch the data from the discovery server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: produit
          uri: http://localhost:8090
          predicates:
            #            when the path contains this it will be redirected into uri
            - Path=/api/v1/produits/**

        - id: commande
          uri: http://localhost:8070
          predicates:
            #            when the path contains this it will be redirected into uri
            - Path=/api/v1/commands/**
#  eureka. client. register-with-eureka Booléen
#  Indique si cette instance doit ou non enregistrer ses informations auprès du serveur eureka pour être découverte par d'autres.
#  Dans certains cas,vous ne souhaitez pas que vos instances soient découvertes alors que vous souhaitez simplement découvrir d'autres instances.
#Par défaut:true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true # Activer la récupération du registre Eureka
    register-with-eureka: true # Enregistrer cette instance dans Eureka


server:
  port: 8222

#to ensure that we get all everything redirected into zipkin
management:
  tracing:
    sampling:
      probability: 1.0
